import Head from "next/head"
import NavBar from "@/components/NavBar"
import Hero from "@/components/Hero"
import Footer from "@/components/Footer"

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>finsweet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="aboutus">
        <NavBar />
        <Hero content={<div className="aboutus-hero">
          <span>About us</span>
          <h1>Building stellar websites for early startups</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
        </div>} image={"/aboutus-hero.webp"} />

        <Footer />
      </main>
    </>
  )
}