import Head from "next/head"
import BlogPostFeatured from "@/components/Blog/BlogPostFeatured"
import BlogPosts from "@/components/Blog/BlogPosts"

export default function Blog() {
  return (
    <>
      <Head>
        <title>finsweet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BlogPostFeatured />
        <BlogPosts />
      </main>
    </>
  )
}
