import Head from "next/head"
import Benefits from "@/components/Benefits"
import Stats from "@/components/Stats"
import DarkHero from "@/components/Hero/DarkHero"
import LightHero from "@/components/Hero/LightHero"

export default function Features() {
  return (
    <>
      <Head>
        <title>finsweet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DarkHero content={<div>
          <h1>All the features you need</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua.</p>

          <button className="primary">View pricing</button>
        </div>} image={"/features-hero.png"} />

        <Stats />
        <Benefits />

        <div className="features-lower-content">
          <LightHero content={<div>
            <span>Use Client-first</span>
            <h1>Top agencies and freelancers around the world use
              Client-first </h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
          </div>} image={"/features-content-hero.jpg"} />
        </div>
      </main>
    </>
  )
}