import Head from "next/head"
import HomepageFeatures from "@/components/Homepage/HomepageFeatures"
import HomepageReview from "@/components/Homepage/HomepageReview"
import DarkHero from "@/components/Hero/DarkHero"

export default function Home() {
  return (
    <>
      <Head>
        <title>finsweet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DarkHero content={<div>
          <h1>Building stellar websites for early startups</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>

          <div className="buttons">
            <button className="primary">View our work</button>
            <button className="secondary">View pricing</button>
          </div>
        </div>} image={"/homepage-hero.png"} />

        <HomepageFeatures />
        <HomepageReview />
      </main>
    </>
  )
}
