import NavBar from "@/components/NavBar"
import Head from "next/head"
import Footer from "@/components/Footer"
import Hero from "@/components/Homepage/Hero"
import HomepageContent from "@/components/Homepage/HomepageContent"
import HomepageReview from "@/components/Homepage/HomepageReview"

export default function Home() {
  return (
    <>
      <Head>
        <title>finsweet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <Hero />
        <HomepageContent />
        <HomepageReview />
        <Footer />
      </main>
    </>
  )
}
